### ISSUE TITLE
about Table 3 in the paper

### ISSUE THREAD

**Issue by jiaw-z** [gallenszl/CFNet#6]
Hello, thanks for the good work.
Just about the Cross-domain generalization evaluation of PSMNet in Table 3.
In the Table 3, the KITTI2015 D1_all of PSMNet trained on Scene Flow datatest  is 16.3, while we got the 28.7, which is far from that reported in your paper. And the pre-trained model from github performances 28.
Wondering the reason about it.
Thanks.

**Comment by gallenszl** [comment]
Hello,
Thank you for your concerns about our work. The d1_all of PSMNet we reported in Table 3 is from the Table 3 of DSMNet[1]. Actually, the PSMNet trained by ourselves also can not achieve such performance. As we afraid this is caused by our own improper implementation, we select to report the better result. The open source URL for DSMNet is  https://github.com/feihuzhang/DSMNet. Maybe you can ask them the rationale?

[1] Zhang, Feihu, et al. "Domain-invariant stereo matching networks." European Conference on Computer Vision. Springer, Cham, 2020.
